

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

format = """îœ‘ $all"""

[username]
style_user = "255"
style_root = "255"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](141) "
disabled = false

[character]
success_symbol = ""
error_symbol = ""

[fill]
symbol = " "

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "â€¦/"
home_symbol = "ï€•"
style = "69 bold"
read_only = " ï ½ "
read_only_style = "white"
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ï˜ "
format = "via [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "â€¦/"
style = "177"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "177"
conflicted = "ï±"
up_to_date = "ï˜«"
untracked = "î¬²"
ahead = "ï…¶${count}"
diverged = "ï½ï…¶${ahead_count}ï…µ${behind_count}"
behind = "ï…µ${count}"
stashed = "ï£– "
modified = "ï£ª"
staged = '[ï­œ\($count\)]($style)'
renamed = "ïª¶ "
deleted = "ï€” "

[nodejs]
symbol = "ï¢˜ "
style = "34"
format = "[$symbol($version )]($style)"

[golang]
symbol = "î˜§ "

[package]
symbol = "ï£– "
disabled = true

[rust]
symbol = "ğŸ¦€ "
